package object

import (
	"context"
	"fmt"

	sccFwMgrClient "github.com/CiscoDevnet/terraform-provider-sccfm/go-client"
	"github.com/CiscoDevnet/terraform-provider-sccfm/go-client/object"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

// ObjectDataSourceConfig defines the type-specific configuration for an object data source.
// M is the Terraform data source model type.
type ObjectDataSourceConfig[M any] struct {
	// TypeNameSuffix is appended to the provider name, e.g. "_network_object".
	TypeNameSuffix string

	// MarkdownDescription is the data source-level description.
	MarkdownDescription string

	// ObjectType is the API object type used for name-based lookup.
	ObjectType object.ObjectType

	// ExtraSchemaAttributes returns the type-specific schema attributes (beyond id, name, description).
	ExtraSchemaAttributes func() map[string]schema.Attribute

	// MapReadOutput maps the API ReadOutput into the model.
	MapReadOutput func(ctx context.Context, output *object.ReadOutput, model *M) error
}

type objectDataSource[M any] struct {
	client *sccFwMgrClient.Client
	config ObjectDataSourceConfig[M]
}

func NewObjectDataSource[M any](config ObjectDataSourceConfig[M]) datasource.DataSource {
	return &objectDataSource[M]{config: config}
}

func (d *objectDataSource[M]) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + d.config.TypeNameSuffix
}

func (d *objectDataSource[M]) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	attrs := map[string]schema.Attribute{
		"id": schema.StringAttribute{
			MarkdownDescription: "The unique identifier of the object. This is a UUID generated by the object service.",
			Computed:            true,
		},
		"name": schema.StringAttribute{
			MarkdownDescription: "The name of the object to look up.",
			Required:            true,
		},
		"description": schema.StringAttribute{
			MarkdownDescription: "A human-readable description of the object.",
			Computed:            true,
		},
	}
	for k, v := range d.config.ExtraSchemaAttributes() {
		attrs[k] = v
	}
	resp.Schema = schema.Schema{
		MarkdownDescription: d.config.MarkdownDescription,
		Attributes:          attrs,
	}
}

func (d *objectDataSource[M]) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*sccFwMgrClient.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("Expected *sccFwMgrClient.Client, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}

	d.client = client
}

func (d *objectDataSource[M]) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var model M
	resp.Diagnostics.Append(req.Config.Get(ctx, &model)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var name types.String
	resp.Diagnostics.Append(req.Config.GetAttribute(ctx, path.Root("name"), &name)...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("reading %s by name: %s", d.config.TypeNameSuffix, name.ValueString()))

	output, err := d.client.ReadObjectByName(ctx, object.ReadByNameInput{
		Name:       name.ValueString(),
		ObjectType: d.config.ObjectType,
	})
	if err != nil {
		resp.Diagnostics.AddError("Failed to read object", err.Error())
		return
	}

	if err := d.config.MapReadOutput(ctx, output, &model); err != nil {
		resp.Diagnostics.AddError("Failed to map object output", err.Error())
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &model)...)
}
