package object

import (
	"context"
	"fmt"

	sccFwMgrClient "github.com/CiscoDevnet/terraform-provider-sccfm/go-client"
	"github.com/CiscoDevnet/terraform-provider-sccfm/go-client/object"
	"github.com/CiscoDevnet/terraform-provider-sccfm/internal/util"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-log/tflog"
)

// ObjectResourceConfig defines the type-specific configuration for an object resource.
// M is the Terraform resource model type (e.g., NetworkObjectModel).
type ObjectResourceConfig[M any] struct {
	// TypeNameSuffix is appended to the provider name, e.g. "_network_object".
	TypeNameSuffix string

	// MarkdownDescription is the resource-level description.
	MarkdownDescription string

	// ExtraSchemaAttributes returns the type-specific schema attributes (beyond id, name, description).
	ExtraSchemaAttributes func() map[string]schema.Attribute

	// BuildCreateInput converts the plan model into an API CreateInput.
	BuildCreateInput func(model *M) (object.CreateInput, error)

	// BuildUpdateInput converts the plan and state models into an API UpdateInput.
	BuildUpdateInput func(plan *M, state *M) (object.UpdateInput, error)

	// MapReadOutput maps the API ReadOutput into the model, setting all fields including type-specific ones.
	MapReadOutput func(ctx context.Context, output *object.ReadOutput, model *M) error

	// GetId extracts the object UID from the model.
	GetId func(model *M) string
}

// CommonSchemaAttributes returns the schema attributes shared by all object resources.
func CommonSchemaAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"id": schema.StringAttribute{
			MarkdownDescription: "The unique identifier of the object. This is a UUID generated by the object service.",
			Computed:            true,
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.UseStateForUnknown(),
			},
		},
		"name": schema.StringAttribute{
			MarkdownDescription: "The name of the object.",
			Required:            true,
		},
		"description": schema.StringAttribute{
			MarkdownDescription: "A human-readable description of the object.",
			Optional:            true,
			Computed:            true,
		},
	}
}

// objectResource is a generic Terraform resource backed by the unified object service.
type objectResource[M any] struct {
	client *sccFwMgrClient.Client
	config ObjectResourceConfig[M]
}

var _ resource.Resource = &objectResource[struct{}]{}

// NewObjectResource creates a new resource.Resource for the given object type configuration.
func NewObjectResource[M any](config ObjectResourceConfig[M]) resource.Resource {
	return &objectResource[M]{config: config}
}

func (r *objectResource[M]) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + r.config.TypeNameSuffix
}

func (r *objectResource[M]) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	attrs := CommonSchemaAttributes()
	for k, v := range r.config.ExtraSchemaAttributes() {
		attrs[k] = v
	}
	resp.Schema = schema.Schema{
		MarkdownDescription: r.config.MarkdownDescription,
		Attributes:          attrs,
	}
}

func (r *objectResource[M]) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*sccFwMgrClient.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *sccFwMgrClient.Client, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}

	r.client = client
}

func (r *objectResource[M]) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {

	typeName := r.config.TypeNameSuffix
	tflog.Trace(ctx, "read "+typeName+" resource")

	var stateData M
	resp.Diagnostics.Append(req.State.Get(ctx, &stateData)...)
	if resp.Diagnostics.HasError() {
		return
	}

	output, err := r.client.ReadObject(ctx, object.ReadInput{
		Uid: r.config.GetId(&stateData),
	})
	if err != nil {
		if util.Is404Error(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("failed to read "+typeName, err.Error())
		return
	}

	if err := r.config.MapReadOutput(ctx, output, &stateData); err != nil {
		resp.Diagnostics.AddError("failed to map "+typeName+" read output", err.Error())
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &stateData)...)
}

func (r *objectResource[M]) Create(ctx context.Context, req resource.CreateRequest, res *resource.CreateResponse) {

	typeName := r.config.TypeNameSuffix
	tflog.Trace(ctx, "create "+typeName+" resource")

	var planData M
	res.Diagnostics.Append(req.Plan.Get(ctx, &planData)...)
	if res.Diagnostics.HasError() {
		return
	}

	createInp, err := r.config.BuildCreateInput(&planData)
	if err != nil {
		res.Diagnostics.AddError("failed to build "+typeName+" create input", err.Error())
		return
	}

	// The unified object service silently discards value.overrides on POST; only
	// PATCH applies override content. Strip overrides from the create payload and
	// re-send them via UpdateObject after the object exists.
	overrides := createInp.Value.Overrides
	createInp.Value.Overrides = nil

	output, err := r.client.CreateObject(ctx, createInp)
	if err != nil {
		res.Diagnostics.AddError("failed to create "+typeName, err.Error())
		return
	}

	if len(overrides) > 0 {
		description := createInp.Description
		output, err = r.client.UpdateObject(ctx, object.UpdateInput{
			Uid:         output.Uid,
			Name:        createInp.Name,
			Description: &description,
			Value: &object.SharedObjectValue{
				ObjectType:     createInp.Value.ObjectType,
				DefaultContent: createInp.Value.DefaultContent,
				Overrides:      overrides,
			},
		})
		if err != nil {
			res.Diagnostics.AddError("failed to apply "+typeName+" overrides after create", err.Error())
			return
		}
	}

	if err := r.config.MapReadOutput(ctx, output, &planData); err != nil {
		res.Diagnostics.AddError("failed to map "+typeName+" create output", err.Error())
		return
	}

	res.Diagnostics.Append(res.State.Set(ctx, &planData)...)
}

func (r *objectResource[M]) Update(ctx context.Context, req resource.UpdateRequest, res *resource.UpdateResponse) {

	typeName := r.config.TypeNameSuffix
	tflog.Trace(ctx, "update "+typeName+" resource")

	var planData M
	res.Diagnostics.Append(req.Plan.Get(ctx, &planData)...)
	if res.Diagnostics.HasError() {
		return
	}

	var stateData M
	res.Diagnostics.Append(req.State.Get(ctx, &stateData)...)
	if res.Diagnostics.HasError() {
		return
	}

	updateInp, err := r.config.BuildUpdateInput(&planData, &stateData)
	if err != nil {
		res.Diagnostics.AddError("failed to build "+typeName+" update input", err.Error())
		return
	}

	output, err := r.client.UpdateObject(ctx, updateInp)
	if err != nil {
		res.Diagnostics.AddError("failed to update "+typeName, err.Error())
		return
	}

	if err := r.config.MapReadOutput(ctx, output, &stateData); err != nil {
		res.Diagnostics.AddError("failed to map "+typeName+" update output", err.Error())
		return
	}

	res.Diagnostics.Append(res.State.Set(ctx, &stateData)...)
}

func (r *objectResource[M]) Delete(ctx context.Context, req resource.DeleteRequest, res *resource.DeleteResponse) {

	typeName := r.config.TypeNameSuffix
	tflog.Trace(ctx, "delete "+typeName+" resource")

	var stateData M
	res.Diagnostics.Append(req.State.Get(ctx, &stateData)...)
	if res.Diagnostics.HasError() {
		return
	}

	uid := r.config.GetId(&stateData)

	// The backend rejects DELETE on an object that still has associated targetIds
	// (overrides cause per-target LocalObjects, and the unified object service
	// auto-attaches CDFMC even for objects without overrides). Re-Read so we
	// detach the current target set rather than trusting potentially stale state.
	current, err := r.client.ReadObject(ctx, object.ReadInput{Uid: uid})
	if err != nil {
		if util.Is404Error(err) {
			return
		}
		res.Diagnostics.AddError("failed to read "+typeName+" before delete", err.Error())
		return
	}

	if len(current.Targets) > 0 {
		targetIds := make([]string, 0, len(current.Targets))
		for _, t := range current.Targets {
			targetIds = append(targetIds, t.Id)
		}
		if err := r.client.DeleteObjectTargets(ctx, object.DeleteTargetsInput{
			Uid:         uid,
			TargetUuids: targetIds,
		}); err != nil {
			res.Diagnostics.AddError("failed to detach "+typeName+" targets before delete", err.Error())
			return
		}
	}

	if err := r.client.DeleteObject(ctx, object.DeleteInput{Uid: uid}); err != nil {
		res.Diagnostics.AddError("failed to delete "+typeName, err.Error())
	}
}
